export default [
    { title: 'Afghanistan', id: 'af', continent: 'Asia' },
    { title: 'Aland Islands', id: 'ax', continent: 'Europe' },
    { title: 'Albania', id: 'al', continent: 'Europe' },
    { title: 'Algeria', id: 'dz', continent: 'Africa' },
    { title: 'American Samoa', id: 'as', continent: 'Oceania' },
    { title: 'Andorra', id: 'ad', continent: 'Europe' },
    { title: 'Angola', id: 'ao', continent: 'Africa' },
    { title: 'Anguilla', id: 'aI', continent: 'North America' },
    { title: 'Antarctica', id: 'aq', continent: 'Antarctica' },
    { title: 'Antigua and Barbuda', id: 'ag', continent: 'North America' },
    { title: 'Argentina', id: 'ar', continent: 'South America' },
    { title: 'Armenia', id: 'am', continent: 'Asia' },
    { title: 'Aruba', id: 'aw', continent: 'North America' },
    { title: 'Australia', id: 'au', continent: 'Oceania' },
    { title: 'Austria', id: 'at', continent: 'Europe' },
    { title: 'Azerbaijan', id: 'az', continent: 'Asia' },
    { title: 'Bahamas', id: 'bs', continent: 'North America' },
    { title: 'Bahrain', id: 'bh', continent: 'Asia' },
    { title: 'Bangladesh', id: 'bd', continent: 'Asia' },
    { title: 'Barbados', id: 'bb', continent: 'North America' },
    { title: 'Belarus', id: 'by', continent: 'Europe' },
    { title: 'Belgium', id: 'be', continent: 'Europe' },
    { title: 'Belize', id: 'bz', continent: 'North America' },
    { title: 'Benin', id: 'bj', continent: 'Africa' },
    { title: 'Bermuda', id: 'bm', continent: 'North America' },
    { title: 'Bhutan', id: 'bt', continent: 'Asia' },
    { title: 'Bolivia', id: 'bo', continent: 'South America' },
    { title: 'Bonaire', id: 'bq', continent: 'North America' },
    { title: 'Bosnia and Herzegovina', id: 'ba', continent: 'Europe' },
    { title: 'Botswana', id: 'bw', continent: 'Africa' },
    { title: 'Bouvet Island', id: 'bv', continent: 'Antarctica' },
    { title: 'Brazil', id: 'br', continent: 'South America' },
    { title: 'British Indian Ocean Territory', id: 'io', continent: 'Asia' },
    { title: 'Brunei', id: 'bn', continent: 'Asia' },
    { title: 'Bulgaria', id: 'bg', continent: 'Europe' },
    { title: 'Burkina Faso', id: 'bf', continent: 'Africa' },
    { title: 'Burundi', id: 'bi', continent: 'Africa' },
    { title: 'Cabo Verde', id: 'cv', continent: 'Africa' },
    { title: 'Cambodia', id: 'kh', continent: 'Asia' },
    { title: 'Cameroon', id: 'cm', continent: 'Africa' },
    { title: 'Canada', id: 'ca', continent: 'North America' },
    { title: 'Cayman Islands', id: 'ky', continent: 'North America' },
    { title: 'Central African Republic', id: 'cf', continent: 'Africa' },
    { title: 'Chad', id: 'td', continent: 'Africa' },
    { title: 'Chile', id: 'cl', continent: 'South America' },
    { title: 'China', id: 'cn', continent: 'Asia' },
    { title: 'Christmas Island', id: 'cx', continent: 'Asia' },
    { title: 'Cocos (Keeling) Islands', id: 'cc', continent: 'Asia' },
    { title: 'Colombia', id: 'co', continent: 'South America' },
    { title: 'Comoros', id: 'km', continent: 'Africa' },
    { title: 'Congo', id: 'cg', continent: 'Africa' },
    { title: 'Cook Islands', id: 'ck', continent: 'Oceania' },
    { title: 'Costa Rica', id: 'cr', continent: 'North America' },
    { title: "Côte d'Ivoire", id: 'ci', continent: 'Africa' },
    { title: 'Croatia', id: 'hr', continent: 'Europe' },
    { title: 'Cuba', id: 'cu', continent: 'North America' },
    { title: 'Curaçao', id: 'cw', continent: 'North America' },
    { title: 'Cyprus', id: 'cy', continent: 'Asia' },
    { title: 'Czechia', id: 'cz', continent: 'Europe' },
    { title: 'Democratic Republic of Congo', id: 'cd', continent: 'Africa' },
    { title: 'Denmark', id: 'dk', continent: 'Europe' },
    { title: 'Djibouti', id: 'dj', continent: 'Africa' },
    { title: 'Dominica', id: 'dm', continent: 'North America' },
    { title: 'Dominican Republic', id: 'do', continent: 'North America' },
    { title: 'Ecuador', id: 'ec', continent: 'South America' },
    { title: 'Egypt', id: 'eg', continent: 'Africa' },
    { title: 'El Salvador', id: 'sv', continent: 'North America' },
    { title: 'Equatorial Guinea', id: 'gq', continent: 'Africa' },
    { title: 'Eritrea', id: 'er', continent: 'Africa' },
    { title: 'Estonia', id: 'ee', continent: 'Europe' },
    { title: 'Eswatini', id: 'sz', continent: 'Africa' },
    { title: 'Ethiopia', id: 'et', continent: 'Africa' },
    { title: 'Falkland Islands', id: 'fk', continent: 'South America' },
    { title: 'Faroe Islands', id: 'fo', continent: 'Europe' },
    { title: 'Fiji', id: 'fj', continent: 'Oceania' },
    { title: 'Finland', id: 'fi', continent: 'Europe' },
    { title: 'France', id: 'fr', continent: 'Europe' },
    { title: 'French Guiana', id: 'gf', continent: 'South America' },
    { title: 'French Polynesia', id: 'pf', continent: 'Oceania' },
    { title: 'French Southern Territories', id: 'tf', continent: 'Antarctica' },
    { title: 'Gabon', id: 'ga', continent: 'Africa' },
    { title: 'Gambia', id: 'gm', continent: 'Africa' },
    { title: 'Georgia', id: 'ge', continent: 'Asia' },
    { title: 'Germany', id: 'de', continent: 'Europe' },
    { title: 'Ghana', id: 'gh', continent: 'Africa' },
    { title: 'Gibraltar', id: 'gi', continent: 'Europe' },
    { title: 'Greece', id: 'gr', continent: 'Europe' },
    { title: 'Greenland', id: 'gl', continent: 'North America' },
    { title: 'Grenada', id: 'gd', continent: 'North America' },
    { title: 'Guadeloupe', id: 'gp', continent: 'North America' },
    { title: 'Guam', id: 'gu', continent: 'Oceania' },
    { title: 'Guatemala', id: 'gt', continent: 'North America' },
    { title: 'Guernsey', id: 'gg', continent: 'Europe' },
    { title: 'Guinea', id: 'gn', continent: 'Africa' },
    { title: 'Guinea-Bissau', id: 'gw', continent: 'Africa' },
    { title: 'Guyana', id: 'gy', continent: 'South America' },
    { title: 'Haiti', id: 'ht', continent: 'North America' },
    { title: 'Heard Island and McDonald Islands', id: 'hm', continent: 'Antarctica' },
    { title: 'Holy See', id: 'va', continent: 'Europe' },
    { title: 'Honduras', id: 'hn', continent: 'North America' },
    { title: 'Hong Kong', id: 'hk', continent: 'Asia' },
    { title: 'Hungary', id: 'hu', continent: 'Europe' },
    { title: 'Iceland', id: 'is', continent: 'Europe' },
    { title: 'India', id: 'in', continent: 'Asia' },
    { title: 'Indonesia', id: 'id', continent: 'Asia' },
    { title: 'Iran', id: 'ir', continent: 'Asia' },
    { title: 'Iraq', id: 'iq', continent: 'Asia' },
    { title: 'Ireland', id: 'ie', continent: 'Europe' },
    { title: 'Isle of Man', id: 'im', continent: 'Europe' },
    { title: 'Israel', id: 'il', continent: 'Asia' },
    { title: 'Italy', id: 'it', continent: 'Europe' },
    { title: 'Jamaica', id: 'jm', continent: 'North America' },
    { title: 'Japan', id: 'jp', continent: 'Asia' },
    { title: 'Jersey', id: 'je', continent: 'Europe' },
    { title: 'Jordan', id: 'jo', continent: 'Asia' },
    { title: 'Kazakhstan', id: 'kz', continent: 'Asia' },
    { title: 'Kenya', id: 'ke', continent: 'Africa' },
    { title: 'Kiribati', id: 'ki', continent: 'Oceania' },
    { title: 'Kosovo', id: 'xk', continent: 'Europe' },
    { title: 'Kuwait', id: 'kw', continent: 'Asia' },
    { title: 'Kyrgyzstan', id: 'kg', continent: 'Asia' },
    { title: 'Laos', id: 'la', continent: 'Asia' },
    { title: 'Latvia', id: 'lv', continent: 'Europe' },
    { title: 'Lebanon', id: 'lb', continent: 'Asia' },
    { title: 'Lesotho', id: 'ls', continent: 'Africa' },
    { title: 'Liberia', id: 'lr', continent: 'Africa' },
    { title: 'Libya', id: 'ly', continent: 'Africa' },
    { title: 'Liechtenstein', id: 'li', continent: 'Europe' },
    { title: 'Lithuania', id: 'lt', continent: 'Europe' },
    { title: 'Luxembourg', id: 'lu', continent: 'Europe' },
    { title: 'Macao', id: 'mo', continent: 'Asia' },
    { title: 'Madagascar', id: 'mg', continent: 'Africa' },
    { title: 'Malawi', id: 'mw', continent: 'Africa' },
    { title: 'Malaysia', id: 'my', continent: 'Asia' },
    { title: 'Maldives', id: 'mv', continent: 'Asia' },
    { title: 'Mali', id: 'ml', continent: 'Africa' },
    { title: 'Malta', id: 'mt', continent: 'Europe' },
    { title: 'Marshall Islands', id: 'mh', continent: 'Oceania' },
    { title: 'Martinique', id: 'mq', continent: 'North America' },
    { title: 'Mauritania', id: 'mr', continent: 'Africa' },
    { title: 'Mauritius', id: 'mu', continent: 'Africa' },
    { title: 'Mayotte', id: 'yt', continent: 'Africa' },
    { title: 'Mexico', id: 'mx', continent: 'North America' },
    { title: 'Micronesia', id: 'fm', continent: 'Oceania' },
    { title: 'Moldova', id: 'md', continent: 'Europe' },
    { title: 'Monaco', id: 'mc', continent: 'Europe' },
    { title: 'Mongolia', id: 'mn', continent: 'Asia' },
    { title: 'Montenegro', id: 'me', continent: 'Europe' },
    { title: 'Montserrat', id: 'ms', continent: 'North America' },
    { title: 'Morocco', id: 'ma', continent: 'Africa' },
    { title: 'Mozambique', id: 'mz', continent: 'Africa' },
    { title: 'Myanmar', id: 'mm', continent: 'Asia' },
    { title: 'Namibia', id: 'na', continent: 'Africa' },
    { title: 'Nauru', id: 'nr', continent: 'Oceania' },
    { title: 'Nepal', id: 'np', continent: 'Asia' },
    { title: 'Netherlands', id: 'nl', continent: 'Europe' },
    { title: 'New Caledonia', id: 'nc', continent: 'Oceania' },
    { title: 'New Zealand', id: 'nz', continent: 'Oceania' },
    { title: 'Nicaragua', id: 'ni', continent: 'North America' },
    { title: 'Niger', id: 'ne', continent: 'Africa' },
    { title: 'Nigeria', id: 'ng', continent: 'Africa' },
    { title: 'Niue', id: 'nu', continent: 'Oceania' },
    { title: 'Norfolk Island', id: 'nf', continent: 'Oceania' },
    { title: 'North Korea', id: 'kp', continent: 'Asia' },
    { title: 'North Macedonia', id: 'mk', continent: 'Europe' },
    { title: 'Northern Mariana Islands', id: 'mp', continent: 'Oceania' },
    { title: 'Norway', id: 'no', continent: 'Europe' },
    { title: 'Oman', id: 'om', continent: 'Asia' },
    { title: 'Pakistan', id: 'pk', continent: 'Asia' },
    { title: 'Palau', id: 'pw', continent: 'Oceania' },
    { title: 'Palestine', id: 'ps', continent: 'Asia' },
    { title: 'Panama', id: 'pa', continent: 'North America' },
    { title: 'Papua New Guinea', id: 'pg', continent: 'Oceania' },
    { title: 'Paraguay', id: 'py', continent: 'South America' },
    { title: 'Peru', id: 'pe', continent: 'South America' },
    { title: 'Philippines', id: 'ph', continent: 'Asia' },
    { title: 'Pitcairn Islands', id: 'pn', continent: 'Oceania' },
    { title: 'Poland', id: 'pl', continent: 'Europe' },
    { title: 'Portugal', id: 'pt', continent: 'Europe' },
    { title: 'Puerto Rico', id: 'pr', continent: 'North America' },
    { title: 'Qatar', id: 'qa', continent: 'Asia' },
    { title: 'Réunion', id: 're', continent: 'Africa' },
    { title: 'Romania', id: 'ro', continent: 'Europe' },
    { title: 'Russia', id: 'ru', continent: 'Europe' },
    { title: 'Rwanda', id: 'rw', continent: 'Africa' },
    { title: 'Saint Barthélemy', id: 'bl', continent: 'North America' },
    { title: 'Saint Helena', id: 'sh', continent: 'Africa' },
    { title: 'Saint Kitts and Nevis', id: 'kn', continent: 'North America' },
    { title: 'Saint Lucia', id: 'lc', continent: 'North America' },
    { title: 'Saint Martin', id: 'mf', continent: 'North America' },
    { title: 'Saint Pierre and Miquelon', id: 'pm', continent: 'North America' },
    { title: 'Saint Vincent and the Grenadines', id: 'vc', continent: 'North America' },
    { title: 'Samoa', id: 'ws', continent: 'Oceania' },
    { title: 'San Marino', id: 'sm', continent: 'Europe' },
    { title: 'São Tomé and Príncipe', id: 'st', continent: 'Africa' },
    { title: 'Saudi Arabia', id: 'sa', continent: 'Asia' },
    { title: 'Senegal', id: 'sn', continent: 'Africa' },
    { title: 'Serbia', id: 'rs', continent: 'Europe' },
    { title: 'Seychelles', id: 'sc', continent: 'Africa' },
    { title: 'Sierra Leone', id: 'sl', continent: 'Africa' },
    { title: 'Singapore', id: 'sg', continent: 'Asia' },
    { title: 'Sint Maarten', id: 'sx', continent: 'North America' },
    { title: 'Slovakia', id: 'sk', continent: 'Europe' },
    { title: 'Slovenia', id: 'si', continent: 'Europe' },
    { title: 'Solomon Islands', id: 'sb', continent: 'Oceania' },
    { title: 'Somalia', id: 'so', continent: 'Africa' },
    { title: 'South Africa', id: 'za', continent: 'Africa' },
    { title: 'South Georgia and the South Sandwich Islands', id: 'gs', continent: 'Antarctica' },
    { title: 'South Korea', id: 'kr', continent: 'Asia' },
    { title: 'South Sudan', id: 'ss', continent: 'Africa' },
    { title: 'Spain', id: 'es', continent: 'Europe' },
    { title: 'Sri Lanka', id: 'lk', continent: 'Asia' },
    { title: 'Sudan', id: 'sd', continent: 'Africa' },
    { title: 'Suriname', id: 'sr', continent: 'South America' },
    { title: 'Svalbard and Jan Mayen', id: 'sj', continent: 'Europe' },
    { title: 'Sweden', id: 'se', continent: 'Europe' },
    { title: 'Switzerland', id: 'ch', continent: 'Europe' },
    { title: 'Syria', id: 'sy', continent: 'Asia' },
    { title: 'Taiwan', id: 'tw', continent: 'Asia' },
    { title: 'Tajikistan', id: 'tj', continent: 'Asia' },
    { title: 'Tanzania', id: 'tz', continent: 'Africa' },
    { title: 'Thailand', id: 'th', continent: 'Asia' },
    { title: 'Timor-Leste', id: 'tl', continent: 'Asia' },
    { title: 'Togo', id: 'tg', continent: 'Africa' },
    { title: 'Tokelau', id: 'tk', continent: 'Oceania' },
    { title: 'Tonga', id: 'to', continent: 'Oceania' },
    { title: 'Trinidad and Tobago', id: 'tt', continent: 'North America' },
    { title: 'Tunisia', id: 'tn', continent: 'Africa' },
    { title: 'Turkey', id: 'tr', continent: 'Europe' },
    { title: 'Turkmenistan', id: 'tm', continent: 'Asia' },
    { title: 'Turks and Caicos Islands', id: 'tc', continent: 'North America' },
    { title: 'Tuvalu', id: 'tv', continent: 'Oceania' },
    { title: 'Uganda', id: 'ug', continent: 'Africa' },
    { title: 'Ukraine', id: 'ua', continent: 'Europe' },
    { title: 'United Arab Emirates', id: 'ae', continent: 'Asia' },
    { title: 'United Kingdom', id: 'gb', continent: 'Europe' },
    { title: 'United States', id: 'us', continent: 'North America' },
    { title: 'Uruguay', id: 'uy', continent: 'South America' },
    { title: 'Uzbekistan', id: 'uz', continent: 'Asia' },
    { title: 'Vanuatu', id: 'vu', continent: 'Oceania' },
    { title: 'Venezuela', id: 've', continent: 'South America' },
    { title: 'Vietnam', id: 'vn', continent: 'Asia' },
    { title: 'Virgin Islands (British)', id: 'vg', continent: 'North America' },
    { title: 'Virgin Islands (U.S.)', id: 'vi', continent: 'North America' },
    { title: 'Wallis and Futuna', id: 'wf', continent: 'Oceania' },
    { title: 'Western Sahara', id: 'eh', continent: 'Africa' },
    { title: 'Yemen', id: 'ye', continent: 'Asia' },
    { title: 'Zambia', id: 'zm', continent: 'Africa' },
    { title: 'Zimbabwe', id: 'zw', continent: 'Africa' }
]